title: jpang7
description: Personal blog and notes
url: "https://jpang7.github.io"
baseurl: ""

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Using custom layouts (no theme)

# Collections
collections:
  apps:
    output: true
    permalink: /apps/:name
  math:
    output: true
    permalink: /math/:name
  progress:
    output: true
    permalink: /progress/:name

# Defaults
defaults:
  - scope:
      path: ""
      type: "apps"
    values:
      layout: "app"
  - scope:
      path: ""
      type: "math"
    values:
      layout: "math"
  - scope:
      path: ""
      type: "progress"
    values:
      layout: "progress"
  - scope:
      path: ""
    values:
      layout: "default"

